### PR TITLE
Enable use of dhcp server instead of link_local

### PR DESCRIPTION
**Pull request by ConnorRigby**
* link local still works
* link local still default

### CODE REVIEW

**Comment by fhunleth** [comment]
This is awesome! I need to try it. I appreciate you keeping link-local as the default, but assuming this works well in practice, I'm probably going to want to make DHCP the default. I'll try to get this into my workflow so that I can give you some feedback. The DHCP library will eventually need to be on hex.pm, but no rush.

**Comment by ConnorRigby** [comment]
The dhcp lib is on hex already actually. There is a PR there then it will need to be bumped.

**Comment by fhunleth** [comment]
Ahh, so once your `elixirize-go!` branch gets merged and a release is made, everything will be good.

**Comment by ConnorRigby** [comment]
Yep. Once that gets merged I'll bump the version in this PR. I just wanted
to get this out there.

**Comment by ConnorRigby** [comment]
@fhunleth I believe this to be ready now that `dhcp_server` is released.

**Comment by GregMefford** [comment]
I've been using this successfully for a while now and I think it makes sense for DHCP to be default  instead of link-local because it works so much more quickly on systems that are configured to wait for DHCP to time-out before falling back to link-local (which seems to be the default most of the time).

**Comment by fhunleth** [comment]
I'm on the same page with using DHCP instead of link local. I've been putting off merging this since I have two issues with using this solution. The first is the license. It's GPL instead of Apache. If we had a small note that the GPL here doesn't "infect" application code running in the Erlang VM then I'm ok. This could just be lack of knowledge for me. I understand OS process boundaries on GPL code, but things get fuzzy to me (and others) when running code in the same OS process like what we're doing here. A note would resolve it. Unfortunately, I'm not sure who all has to be ok with the note and if they're even available. The second issue is that I'd prefer a solution that just grants one IP address out (since that's all there is for gadget mode) with no fuss. This server has quite a few unneeded features and it's missing one important feature and that's the ability to play nicely if you plug multiple Pi Zero's into your laptop/PC at the same time. I started a project that does this a while ago, but timed out. I intend to get back to it.

**Comment by GregMefford** [comment]
@ConnorRigby I'm curious if/how I can help get this landed because I've been using this branch in my training for a while and I love having DHCP work so easily over gadget mode. Is it just a matter of making some notes in the README about the GPL thing Frank raised? I'm not a licensing expert, so I'm not 100% clear on how to explain that sufficiently and accuratley.

**Comment by ConnorRigby** [comment]
I think @fhunleth was going to circle back on it when he gets a chance :tm: but basically i believe we wanted to get rid of a lot of the functionality in the dhcp_server lib. There was also an issue of being able to get deterministic addresses for the cases of mdns not working.

**Comment by fhunleth** [comment]
Mind if we close this now?

**Pull request closed without merging**
