### PR TITLE
Switch to module childspecs

### PR DESCRIPTION
**Pull request by GregMefford**
This is some clean-up that I split out of #32.

### CODE REVIEW

**Comment by fhunleth** [comment]
@GregMefford Please break this into three PRs.

**Comment by GregMefford** [comment]
👍 Split!

**Review by ConnorRigby — CHANGES_REQUESTED** [review]
Since Nerves only relies on 1.4 i don't think we can do this, since its not backwards compatible right?

**Comment by GregMefford** [comment]
`nerves_init_gadget` says that is depends on Elixir 1.6, so I figure this is fine.
Obviously not a huge deal to make this change if you think people will want to run it on older versions of Elixir, but if they did, they'd already get a warning/error message: https://github.com/nerves-project/nerves_init_gadget/blob/master/mix.exs#L16

**Comment by fhunleth** [comment]
Regarding 1.4, I've been updating things to 1.6 since we don't have any regular testing on that version.

**Review by fhunleth — APPROVED** [review]

**Pull request merged**
