### PR TITLE
Support one_dhcp and update docs

### PR DESCRIPTION
**Pull request by fhunleth**

### CODE REVIEW

**Comment by ConnorRigby** [comment]
i _just happened_ to be testing this out literally right now. Seems to be working for me.

**Review by ConnorRigby — APPROVED** [review]

**Comment by fhunleth** [comment]
@ConnorRigby What platform/config did you test?

**Comment by ConnorRigby** [comment]
I started a brand new project with `mix nerves.new hello_nerves --target=rpi0 --init-gadget`

* Elixir 1.6.6
* OTP 21.0.4
* host:  Arch Linux, NetworkManager etc
* target: rpi0

**Review by mobileoverlord — APPROVED** [review]
❤️

**Pull request merged**
